import { Client, handle_file } from "https://cdn.jsdelivr.net/npm/@gradio/client/dist/index.min.js";

// Official AI4Bharat IndicF5 Space. It currently runs on Hugging Face ZeroGPU.
const SPACE = "ai4bharat/IndicF5";
const LOCAL_API = "http://127.0.0.1:8000";
const IS_LOCAL = ["localhost", "127.0.0.1"].includes(window.location.hostname);

let clientPromise;

async function getHFClient() {
  if (!clientPromise) {
    clientPromise = Client.connect(SPACE, {
      status_callback: (status) => {
        window.dispatchEvent(new CustomEvent("audiolab-hf-status", { detail: status }));
      },
    });
  }
  return clientPromise;
}

async function localHealth() {
  const response = await fetch(`${LOCAL_API}/health`);
  if (!response.ok) throw new Error(`Local backend returned ${response.status}`);
  return response.json();
}

async function localAnalyze(file) {
  const form = new FormData();
  form.append("file", file, file.name || "reference.wav");
  const response = await fetch(`${LOCAL_API}/analyze`, { method: "POST", body: form });
  if (!response.ok) throw new Error(await response.text());
  return response.json();
}

async function browserAnalyze(file) {
  const context = new AudioContext();
  try {
    const buffer = await context.decodeAudioData(await file.arrayBuffer());
    const channel = buffer.getChannelData(0);
    let sum = 0;
    let silent = 0;
    const threshold = 0.01;
    const sampleStep = Math.max(1, Math.floor(channel.length / 50000));
    let count = 0;
    for (let i = 0; i < channel.length; i += sampleStep) {
      const v = channel[i];
      sum += v * v;
      if (Math.abs(v) < threshold) silent++;
      count++;
    }
    const rms = Math.sqrt(sum / Math.max(1, count));
    const silence = silent / Math.max(1, count);
    const score = Math.max(0, Math.min(100, Math.round(100 - silence * 55 + Math.min(rms * 180, 35))));
    return {
      duration: Number(buffer.duration.toFixed(2)),
      rms: Number(rms.toFixed(4)),
      silence,
      score,
    };
  } finally {
    await context.close();
  }
}

async function localGenerate({ text, language, refText, file }) {
  const form = new FormData();
  form.append("text", text);
  form.append("language", language);
  form.append("ref_text", refText);
  form.append("file", file, file.name || "reference.wav");
  const response = await fetch(`${LOCAL_API}/generate`, { method: "POST", body: form });
  if (!response.ok) {
    let message = `Local backend returned ${response.status}`;
    try {
      const body = await response.json();
      message = body.error || message;
    } catch (_) {}
    throw new Error(message);
  }
  return response.blob();
}

if (IS_LOCAL) {
  window.audiolabHFReady = Promise.resolve();
  window.audiolabHF = {
    health: localHealth,
    analyze: localAnalyze,
    generate: localGenerate,
  };
} else {
  window.audiolabHFReady = getHFClient();
  window.audiolabHF = {
    async health() {
      const client = await getHFClient();
      return client.view_api();
    },

    // The official IndicF5 Space has no /analyze endpoint, so analyze the
    // reference locally in the browser before sending it to the model.
    async analyze(file) {
      return browserAnalyze(file);
    },

    async generate({ text, refText, file }) {
      const client = await getHFClient();
      // IndicF5 exposes the Gradio event generated by
      // submit_btn.click(synthesize_speech, ...).
      return client.predict(
        text,
        handle_file(file),
        refText,
        { api_name: "/synthesize_speech" }
      );
    },
  };
}
