(function(){
const API=(window.AUDIOLAB_API_URL||'/api').replace(/\/$/,'');
let file=null,audio=null,url=null,undo=[],redo=[],start=0,end=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=s=>{s=Number(s)||0;return `${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toFixed(3).padStart(6,'0')}`};
function page(){return `<div class="hero"><div><div class="eyebrow">Audiolab / Professional Audio Studio</div><h1>Your audio. Your timeline. Your control.</h1><p>Waveform editing, precision selection, AI cleanup, playback and export in one local-first workspace.</p></div><div class="actions"><label class="btn primary file-button">Open Audio<input id="studioFile" type="file" accept="audio/*"></label><button class="btn secondary" id="recordHint">Record</button></div></div>
<div class="studio-pro card"><div class="pro-head"><div><strong id="studioFileName">No audio loaded</strong><div class="dim" id="studioMeta">Open a recording to start editing.</div></div><div class="actions"><span class="status" id="studioState">Ready</span><button class="tool-btn" id="undoBtn">↶ Undo</button><button class="tool-btn" id="redoBtn">Redo ↷</button></div></div>
<div class="timeline-wrap"><div class="ruler"><span>00:00</span><span id="studioDuration">00:00</span></div><div class="wave-editor" id="studioWave"><div class="wave-empty">Open an audio file to see its waveform</div><canvas id="studioCanvas"></canvas><div id="studioSelection"></div><div id="studioPlayhead"></div></div></div>
<div class="transport"><button class="round" id="studioPlay">▶</button><button class="round" id="studioStop">■</button><span id="studioCurrent">00:00.000</span><input id="studioSeek" type="range" min="0" max="1000" value="0" class="range"><span id="zoomLabel">1×</span><input id="studioZoom" type="range" min="1" max="5" step="1" value="1" class="range zoom"></div>
<div class="selection-bar"><div><label>Selection start</label><input id="selStart" type="number" min="0" step="0.001" value="0"></div><div><label>Selection end</label><input id="selEnd" type="number" min="0" step="0.001" value="0"></div><button class="btn secondary" id="applySelection">Apply</button><span id="selectionInfo">No selection</span></div>
<div class="editor-tools"><button data-op="trim">✂ Trim to selection</button><button data-op="silence">⌁ Remove Silence</button><button data-op="normalize">◒ Normalize</button><button data-op="enhance">✦ Enhance Voice</button><button data-op="fade">↗ Fade In/Out</button><button data-op="reverse">↔ Reverse</button><button data-op="speed">1.15× Speed</button><button data-op="pitch">♬ +1 Pitch</button></div>
<div class="pro-footer"><div><b>Non-destructive workflow</b><span>Each operation creates a new WAV and keeps the current workspace ready for the next edit.</span></div><div class="actions"><button id="qualityBtn" class="btn secondary">✓ Analyze Quality</button><button id="exportBtn" class="btn primary">Export WAV</button></div></div><div id="qualityPanel"></div></div>
<div class="card export-card"><div><div class="eyebrow">Preview</div><h3>Listen before export</h3></div><audio id="studioAudio" controls></audio><a id="studioDownload" class="btn primary disabled-link" download="audiolab-output.wav">Download WAV</a></div>`}
function draw(){const c=document.getElementById('studioCanvas'),box=document.getElementById('studioWave');if(!c||!audio?.buffer)return;c.width=box.clientWidth*devicePixelRatio;c.height=190*devicePixelRatio;const x=c.getContext('2d');x.scale(devicePixelRatio,devicePixelRatio);const w=box.clientWidth,h=190;x.clearRect(0,0,w,h);const d=audio.buffer.getChannelData(0),bars=Math.max(200,Math.floor(w/3)),step=Math.max(1,Math.floor(d.length/bars));x.beginPath();for(let i=0;i<bars;i++){let m=0;for(let j=i*step;j<Math.min(d.length,(i+1)*step);j+=2)m=Math.max(m,Math.abs(d[j]));const xx=i/bars*w,a=m*78;x.moveTo(xx,95-a);x.lineTo(xx,95+a)}x.stroke();const l=start/audio.duration*w,r=end/audio.duration*w;x.fillStyle='rgba(20,20,20,.08)';x.fillRect(0,0,l,h);x.fillRect(r,0,w-r,h);const p=audio.currentTime/audio.duration*w;const ph=document.getElementById('studioPlayhead');if(ph)ph.style.left=p+'px';}
function updateSelection(){if(!audio)return;start=Math.max(0,Math.min(Number(document.getElementById('selStart').value)||0,audio.duration));end=Math.max(start,Math.min(Number(document.getElementById('selEnd').value)||audio.duration,audio.duration));document.getElementById('selStart').value=start.toFixed(3);document.getElementById('selEnd').value=end.toFixed(3);document.getElementById('selectionInfo').textContent=`Selected ${fmt(end-start)}`;draw()}
function output(blob,name){if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(blob);document.getElementById('studioAudio').src=url;const d=document.getElementById('studioDownload');d.href=url;d.download=name;d.classList.remove('disabled-link')}
async function process(op){if(!file){window.toast?.('Open an audio file first');return}undo.push({start,end});redo=[];const st=document.getElementById('studioState');st.textContent='Processing…';const fd=new FormData();fd.append('file',file,file.name);fd.append('start',String(start));fd.append('end',String(end));fd.append('fade_in','0.4');fd.append('fade_out','0.6');fd.append('rate',op==='speed'?'1.15':'1');fd.append('semitones',op==='pitch'?'1':'0');try{const r=await fetch(`${API}/edit/${op}`,{method:'POST',body:fd});if(!r.ok)throw Error(await r.text());const blob=await r.blob();file=new File([blob],`audiolab-${op}.wav`,{type:'audio/wav'});output(blob,file.name);loadAudioElement(file);st.textContent='Complete'}catch(e){st.textContent='Error';window.toast?.('Processing failed. Check the local backend.')}}
function loadAudioElement(f){if(audio?.element)audio.element.pause();const u=URL.createObjectURL(f);const el=new Audio(u);audio={element:el,duration:0,buffer:null};el.onloadedmetadata=()=>{audio.duration=el.duration;start=0;end=el.duration;document.getElementById('selEnd').value=end.toFixed(3);document.getElementById('studioDuration').textContent=fmt(end);decode(f)};el.ontimeupdate=()=>{document.getElementById('studioCurrent').textContent=fmt(el.currentTime);document.getElementById('studioSeek').value=el.duration?el.currentTime/el.duration*1000:0;draw()}}
async function decode(f){try{const ac=new AudioContext();audio.buffer=await ac.decodeAudioData(await f.arrayBuffer());document.getElementById('studioMeta').textContent=`${(f.size/1048576).toFixed(2)} MB · ${f.type||'audio'} · ${fmt(audio.duration)}`;draw()}catch{}}
async function quality(){if(!file){window.toast?.('Open an audio file first');return}const p=document.getElementById('qualityPanel');p.innerHTML='<div class="loading">Analyzing audio…</div>';const fd=new FormData();fd.append('file',file);try{const r=await fetch(`${API}/quality`,{method:'POST',body:fd});const q=await r.json();p.innerHTML=`<div class="quality-grid"><div><small>Quality score</small><b>${esc(q.quality_score)}%</b></div><div><small>Duration</small><b>${esc(q.duration)}s</b></div><div><small>Clipping</small><b>${(q.clipping_ratio*100).toFixed(1)}%</b></div><div><small>Silence</small><b>${(q.silence_ratio*100).toFixed(1)}%</b></div></div>`}catch{p.innerHTML='<div class="dim">Quality analysis unavailable.</div>'}}
function bind(){const f=document.getElementById('studioFile');f.onchange=()=>{file=f.files?.[0];if(file){document.getElementById('studioFileName').textContent=file.name;loadAudioElement(file)}};document.getElementById('studioPlay').onclick=()=>audio?.element&&(audio.element.paused?audio.element.play():audio.element.pause());document.getElementById('studioStop').onclick=()=>{if(audio?.element){audio.element.pause();audio.element.currentTime=0}};document.getElementById('studioSeek').oninput=e=>audio?.element&&(audio.element.currentTime=Number(e.target.value)/1000*audio.duration);document.getElementById('studioCanvas').onclick=e=>{if(!audio?.duration)return;const r=e.currentTarget.getBoundingClientRect();const t=(e.clientX-r.left)/r.width*audio.duration;document.getElementById('selStart').value=Math.min(t,end).toFixed(3);updateSelection()};document.getElementById('selStart').oninput=updateSelection;document.getElementById('selEnd').oninput=updateSelection;document.getElementById('applySelection').onclick=updateSelection;document.getElementById('studioZoom').oninput=e=>document.getElementById('zoomLabel').textContent=e.target.value+'×';document.getElementById('qualityBtn').onclick=quality;document.getElementById('exportBtn').onclick=()=>{if(file)output(new Blob([file],{type:'audio/wav'}),'audiolab-export.wav')};document.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>process(b.dataset.op));document.getElementById('recordHint').onclick=()=>document.querySelector('.nav-item[data-page="voices"]')?.click();document.getElementById('undoBtn').onclick=()=>{const x=undo.pop();if(x){redo.push({start,end});start=x.start;end=x.end;document.getElementById('selStart').value=start;document.getElementById('selEnd').value=end;updateSelection()}};document.getElementById('redoBtn').onclick=()=>{const x=redo.pop();if(x){undo.push({start,end});start=x.start;end=x.end;document.getElementById('selStart').value=start;document.getElementById('selEnd').value=end;updateSelection()}};window.addEventListener('resize',draw)}
const oldRender=window.render;window.render=function(){oldRender?.();if(window.state?.page==='tools'){document.getElementById('page-tools').innerHTML=page();bind()}};
})();